easy_admin:
  design:
    form_theme:
      - '@EasyAdmin/form/bootstrap_4.html.twig'
      - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
  entities:
    Sheet:
      class: App\Entity\Sheet
      label: Sheet
      form:
        fields:
          - title
          - { property: 'content', type: 'fos_ckeditor' }
    Tutorial:
      class: App\Entity\Tutorial
      label: Tutorial
      form:
        fields:
          - title
          - { property: 'content', type: 'fos_ckeditor' }
