version: '3.8'
services:
  traefik:
    image: traefik:2.5
    command:
      # Globals
      - "--global.checkNewVersion=true"
      - "--global.sendAnonymousUsage=true"
      # Http & Https
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      # Permits the update by user's services
      - "--api=true"
      # Docker Configuration
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=proxy"
      - "--providers.docker.swarmMode=false"
      # Certificate Resolver
      - "--certificatesResolvers.lets-encrypt.acme.email=quentin.adadain@gmail.com"
      - "--certificatesresolvers.lets-encrypt.acme.storage=/etc/traefik/acme.json"
      - "--certificatesresolvers.lets-encrypt.acme.httpchallenge.entrypoint=web"
      - "--serverstransport.insecureskipverify=true"
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - "./traefik:/etc/traefik"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  web:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    labels:
      # The labels are usefull for Traefik only
      - "traefik.enable=true"
      # http
      - "traefik.http.routers.httpcrook.entrypoints=web"
      - "traefik.http.routers.httpcrook.rule=Host(`www.crook.fr`) || Host(`crook.fr`)"
      - "traefik.http.routers.httpcrook.service=httpcrook-service"
      - "traefik.http.services.httpcrook-service.loadbalancer.server.port=8080"
      # Middlewares
      # Redirect these routes to https
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.httpcrook.middlewares=redirect-to-https"
      # https
      - "traefik.http.routers.httpscrook.entrypoints=websecure"

      # https
      - "traefik.http.routers.httpscrook.rule=Host(`www.crook.fr`) || Host(`crook.fr`)"
      - "traefik.http.routers.httpscrook.service=httpscrook-service"
      - "traefik.http.services.httpscrook-service.loadbalancer.server.port=8080"
      # SSL
      - "traefik.http.routers.httpscrook.tls=true"
      - "traefik.http.routers.httpscrook.tls.certresolver=lets-encrypt"

  node:
    image: node:12-alpine
    command: sh -c "yarn install && yarn encore dev --watch"
    volumes:
      - .:/app:cached
    working_dir: /app
