version: '3.8'
services:
  traefik:
    image: traefik:2.6
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=quentin.adadain@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
    restart: always
    ports:
      - '80:85'
      - '443:443'
    volumes:
      - "./traefik:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  web:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./traefik:/var/www/html/traefik
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.my-app.rule=Host(`crook.fr`, `www.crook.fr`)'
      - "traefik.http.routers.my-app.entrypoints=websecure"
      - "traefik.http.routers.my-app.tls.certresolver=myresolver"

    ports:
      - "85:8080"

  node:
    image: node:12-alpine
    command: sh -c "yarn install && yarn encore dev --watch"
    volumes:
      - .:/app:cached
    working_dir: /app
